steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git config --global advice.detachedHead false
      git clone https://github.com/veeresh08/Handball-Blog.git .
      git fetch origin master:refs/remotes/origin/master
      git checkout FETCH_HEAD
      # Additional commands as necessary
  - name: 'python:3.8-slim'
    args: ['python', 'main.py']
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Ensure all logs are captured in Cloud Logging
