steps:
  # Step to explicitly configure Git and force initialization
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git config --global init.defaultBranch
      git init
      git remote add origin https://github.com/veeresh08/Handball-Blog.git
      git fetch
      git checkout FETCH_HEAD
      # See if any hints are issued during these operations

  # Your existing Python step
  - name: 'python:3.8-slim'
    args: ['python', 'main.py']

options:
  logging: 'CLOUD_LOGGING_ONLY'  # This setting ensures logs go to Cloud Logging
