steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Suppress git hint messages by setting default branch name globally
      git config --global init.defaultBranch main
      # Proceed with other git commands
      git clone https://github.com/veeresh08/Handball-Blog.git .
      git fetch origin master:refs/remotes/origin/master
      git checkout FETCH_HEAD
  - name: 'python:3.8-slim'
    args: ['python', 'main.py']
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Ensure all logs are captured in Cloud Logging
